# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^.pre-commit-config.yaml
fail_fast: true
repos:
-   repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "--output-mode", "inject", "."]
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-list=false
          - --args=-write=true
#      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--disable-rule=terraform_module_pinned_source
          - --args=--disable-rule=terraform_required_providers
          - --args=--disable-rule=terraform_required_version
          - --args=--disable-rule=terraform_unused_declarations
          - --args=--disable-rule=terraform_typed_variables
#      - id: terraform_checkov
#        args:
#          - --args=--quiet
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
